services:
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./backend:/var/www/html
    environment:
      PHP_MEMORY_LIMIT: 512M
    networks:
      - quotter

  nginx:
    image: nginx:1.28-alpine
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php #php-fpmと通信するためphpコンテナの後に起動する必要がある
    networks:
      - quotter

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - quotter

volumes:
  data:
networks:
  quotter:
    driver: bridge
